Solved tasks with arrays
MelixoFF/ru-study-ruby-forDB pull request #1
Opened 2022-10-27 12:58 UTC by MelixoFF

2022-10-27 18:02 UTC, greybutton requested changes

2022-10-27 18:02 UTC, greybutton commented on test/exercise/arrays/solution.rb
> +        def findMax(array)
1 объявлять функцию внутри функции не стоит
2 у руби другое соглашение об именовании, функций и переменных

2022-10-27 18:02 UTC, greybutton commented on test/exercise/arrays/solution.rb
> +      def search(array, query)
попробуйте через рекурсию сделать

2022-10-28 15:41 UTC, MelixoFF commented on test/exercise/arrays/solution.rb
> +        def findMax(array)
I know that declaring functions inside each other isn't a good idea, but for this test it's much easier to do like that

2022-10-28 15:44 UTC, MelixoFF commented on test/exercise/arrays/solution.rb
> +      def search(array, query)
I don't like this realization with recursive function due to necessity of changing 2 parameters (left edge and right edge) but i've done it

2022-10-28 18:07 UTC, greybutton commented on test/exercise/arrays/solution.rb
> +        def findMax(array)
what do you mean by that? how inside can be easier than outside? the place does not affect function declaration

2022-10-28 18:11 UTC, greybutton commented on test/exercise/arrays/solution.rb
> +      def search(array, query)
okay, cool. but I think you kind of overthinking that solution. for example, you can set left_edge = 0 and right_edge = array.length - 1 by default. and I would say a perfect solution for the search is 4 lines of code. I don't ask you to do it in 4 lines, just some improvements if you don't mind

2022-11-01 13:10 UTC, ilya-shakirov requested changes

2022-11-01 13:10 UTC, ilya-shakirov commented on test/exercise/arrays/solution.rb
> +          if el>max_value
`el > max_value`

2022-11-01 13:10 UTC, ilya-shakirov commented on test/exercise/arrays/solution.rb
> +            max_value=el
max_value = el

2022-11-01 13:10 UTC, ilya-shakirov commented on test/exercise/arrays/solution.rb
> +        return array.map{|el| el>0 ? find_max(array) : el}
array.map { |el| el>0 ? find_max(array) : el }
Линтер не ругается на пробелы?

2022-11-01 13:10 UTC, ilya-shakirov commented on test/exercise/arrays/solution.rb
> +        return array[centre]>=query ? search(array[0,centre], query, left_edge)
сделай через 
```
if pred
  return 1
else
  return 2
end
```
не стоит злоупотреблять тернарками, если строчки длинные получаются

2022-11-02 08:18 UTC, MelixoFF commented on test/exercise/arrays/solution.rb
> +        return array.map{|el| el>0 ? find_max(array) : el}
No it doesn't

2022-11-03 08:47 UTC, closed without merging